cc_test (
    name = "project1_test",
    srcs = [
        "project1_test.cpp",
    ],
    deps = [
        "//src:libproject1",
        "@com_google_googletest//:gtest_main",
    ],
    data = [
    ],
)